### ISSUE TITLE
Lazy initialization of mutex is thread unsafe

### ISSUE THREAD

**Issue by ioquatix** [discordrb/discordrb#707] opened 2020-03-27 01:48 UTC
https://github.com/discordrb/discordrb/blob/2c2b50e32c055aa8288b34644346a10696d5efa1/lib/discordrb/api.rb#L105

I'm not sure how to fix this but... this definitely looks unsafe.

**Comment by z64** [comment] 2020-03-27 01:55
Could you give more context to what you believe is "unsafe", just so that I fully understand your comment?

At the very least because of how Discord rate-limiting works, I don't see any noticeable fallout happening even if two threads race to create a new mutex for the same key.

**Comment by headius** [comment] 2020-03-27 02:22
The problem is that you may have two threads create their own mutexes and then proceed to do work in parallel that was supposed to happen serially.

**Comment by ioquatix** [comment] 2020-03-27 02:24
Not only that, but modifying a shared hash table without holding a mutex can cause the hash table to become corrupt.

**Comment by z64** [comment] 2020-03-27 02:26
Yes, I understand that much. Again, because of how Discord's rate-limiting works, this is ultimately inconsequential, and at worst cheap - there are very few (I can only think of one) endpoint that does not allow for at least two parallel requests. The worst case scenario, the user gets a 429, and then this never happens again once there is only one surviving mutex. This is tolerable, and has never adversely affected anyone to my knowledge over the past 3 or 4 years.

**Comment by ioquatix** [comment] 2020-03-27 02:27
The worst case is your program crashes.

**Comment by z64** [comment] 2020-03-27 02:32
If you have a reproducible example of such a case with our library, I'd be happy to investigate a more immediate action.

All of our RL code is due for a rewrite in the near future anyway because of new data available to us in Discord's API, so I'm not interested in spending so much time investigating this when it all will be ripped out, and no bots to our knowledge have ever had such a drastic consequence.

**Comment by ioquatix** [comment] 2020-03-27 02:36
@headius @eregon do you have a crash repro on JRuby for parallel modification of a shared hash table? I know I've seen it blow up in the past. Maybe it was rubinius, which at least you can argue no one cares about much these days.

**Comment by ioquatix** [comment] 2020-03-27 02:37
Also @z64, I don't use discord, so it's not really on me to spend hours trying to make a repro, unless you want to pay me to do an audit. Otherwise, this is about as far as I have time to take it. You can do what you like with the report, i.e. close it, it won't bother me, but at least you are aware of it which was my main intention.

**Comment by z64** [comment] 2020-03-27 02:40
I will note that we do not officially support the use of JRuby or TruffleRuby. We don't test against it in CI, and none of our maintainers has any experience with it (myself including).

And that's fine @ioquatix, I do actually appreciate the concern. I've always known our concurrency story to be very awkward when I inherited maintaining the library, and its something I hope to improve over time.

**Comment by ioquatix** [comment] 2020-03-27 02:46
Let me know if you are ever interested in rewriting something from the ground up with `async`.

**Comment by z64** [comment] 2020-03-27 02:51
Yep, I've looked at and considered your async libs in the past - very interesting stuff. I'm not 100% sure if it fits with what we want to deliver with `discordrb` just yet, but we have many other problems to solve first. I'll probably try it at some point when we're ready to re-evaluate more of our internals at that level. (:spaghetti:)

I'll close this for now, as discussed I don't think there's anything actionable here yet.

**Closed by z64** 2020-03-27 02:51 UTC

**Comment by eregon** [comment] 2023-03-09 21:30
> @headius @eregon do you have a crash repro on JRuby/TruffleRuby for parallel modification of a shared hash table? I know I've seen it blow up in the past. Maybe it was rubinius, which at least you can argue no one cares about much these days.

To close the loop, there is such a reproduction of entries being lost in https://www.youtube.com/watch?v=Wu9LRNOc5pQ
As @ioquatix shows this can clearly lose mutexes.
In fact it can also happen on CRuby, it depends what's the class of the key and other subtlety but overall it's just unsafe.
You would want to use concurrent-ruby's Concurrent::Map if you want a to use a thread-safe Hash.

Accessing a Hash in parallel is thread-unsafe, per the Ruby Memory Model.

Here is a quick repro I did:
```ruby
require 'etc'

T = Etc.nprocessors * 2
N = 10_000

H = {}
$go = false
q = Queue.new

threads = T.times.map { |t|
  Thread.new {
    q << true
    Thread.pass until $go
    N.times { |i|
      H[t * N + i] = true
    }
  }
}

T.times { q.pop }
sleep 0.1
$go = true

threads.each(&:join)
p H.size
```

It can get output like:
```
ruby 3.1.3p185 (2022-11-24 revision 1a6b16756e) [x86_64-linux]
320000
jruby 9.4.0.0 (3.1.0) 2022-11-23 95c0ec159f OpenJDK 64-Bit Server VM 17.0.6+10 on 17.0.6+10 +jit [x86_64-linux]
319920
jruby 9.4.0.0 (3.1.0) 2022-11-23 95c0ec159f OpenJDK 64-Bit Server VM 17.0.6+10 on 17.0.6+10 +jit [x86_64-linux]
319857
truffleruby 23.0.0-dev-82f5ec31, like ruby 3.1.3, GraalVM CE Native [x86_64-linux]
java.lang.RuntimeException: Ruby Thread id=59 from parallel_hash.rb:11 terminated with internal error:
...
Caused by: java.lang.NullPointerException
	at org.truffleruby.core.hash.library.PackedHashStoreLibrary.getHashed(PackedHashStoreLibrary.java:75)
...
```

So CRuby's GIL will as a side effect avoid the problem on this particular example.
You could think JRuby/TruffleRuby are not "compatible" here but in fact when such an error happens it's almost always a concurrency bug in the gem, like this issue.
And CRuby's GIL rarely avoids real concurrency problems, for instance it does not avoid double assignment for the same key with the same Mutex.
You can see this in https://bugs.ruby-lang.org/issues/19237, which shows a similar problem on CRuby.
