### ISSUE TITLE
Gateway raises exception when server is deleted

### ISSUE THREAD

**Issue by jcraigk** [discordrb/discordrb#725] opened 2020-05-22 03:14 UTC
# Summary

When a gateway listener receives a deletion event from a server, it produces the following error, whether or not the `bot.server_delete` event is being listened for.

```
Discord using gateway protocol version: 6, requested: 6
Gateway message error!
Exception: #<NoMethodError: undefined method `map' for nil:NilClass>
/discordrb-3.3.0/lib/discordrb/data.rb:2896:in `initialize'
/discordrb-3.3.0/lib/discordrb/events/guilds.rb:64:in `new'
/discordrb-3.3.0/lib/discordrb/events/guilds.rb:64:in `init_server'
/discordrb-3.3.0/lib/discordrb/events/guilds.rb:15:in `initialize'
/discordrb-3.3.0/lib/discordrb/bot.rb:1233:in `new'
/discordrb-3.3.0/lib/discordrb/bot.rb:1233:in `handle_dispatch'
/discordrb-3.3.0/lib/discordrb/bot.rb:654:in `dispatch'
/discordrb-3.3.0/lib/discordrb/gateway.rb:714:in `handle_dispatch'
/discordrb-3.3.0/lib/discordrb/gateway.rb:679:in `handle_message'
/discordrb-3.3.0/lib/discordrb/gateway.rb:617:in `websocket_loop'
/discordrb-3.3.0/lib/discordrb/gateway.rb:569:in `connect'
/discordrb-3.3.0/lib/discordrb/gateway.rb:463:in `block in connect_loop'
/discordrb-3.3.0/lib/discordrb/gateway.rb:462:in `loop'
/discordrb-3.3.0/lib/discordrb/gateway.rb:462:in `connect_loop'
/discordrb-3.3.0/lib/discordrb/gateway.rb:168:in `block in run_async'
```

It's not clear to me which line of source is actually causing the error due to how `data.rb` is constructed (there is no actual line 2896 - `data.rb` is just a list of `require`s).

## Environment

Mac OSX Catalina
ruby 2.6.6p146 (2020-03-31 revision 67876) [x86_64-darwin19]
discordrb (3.3.0)

**Comment by z64** [comment] 2020-05-22 03:18
Hi, thanks for reporting. This is a duplicate of https://github.com/discordrb/discordrb/issues/684 and is fixed in https://github.com/discordrb/discordrb/commit/bb457fe981d2b997b704ad85008ec3b185b046e8.

The `data.rb` file was split into multiple files following the release of v3.3.0 - you have to browse the tag in order to locate the specific line if you get a backtrace from that file.

**Closed by z64** 2020-05-22 03:18 UTC

**Comment by jcraigk** [comment] 2020-05-22 03:31
Thanks for incredibly fast response and sorry for dupe issue (I only searched open issues - my bad).

Just a bit of feedback: using the sha mentioned, I'm seeing that when capturing the event data in `bot.server_delete`, the server id comes back as `event.server` whereas most other event blocks expose this as `event.server.id`. Maybe not a bug, just unexpected as a user of the gem.

**Comment by z64** [comment] 2020-05-22 03:49
No worries. And, that is basically was the issue - Discord (mistakenly) gave you a full server object when a server was deleted when it was documented to only give you the server ID. As such we can't furnish the whole server object, because we aren't given the full object anymore.  With the current caching mechanisms that discordrb uses, we release our reference to the server data before calling event handlers - so the lib can't directly provide its last known data either.

The recommended approaches for these kinds of scenarios is to:
- a) Override the internal event handler method to access the data before it is dropped from the cache https://github.com/discordrb/discordrb/blob/master/lib/discordrb/bot.rb#L925-L929
```rb
class Discordrb::Bot
  def delete_guild(id)
    deleted_server = @servers.delete(id)
    # do something with deleted_server
  end
end
```
You could also subclass `Discordrb::Bot` if you don't want to reopen it directly.

- b) Hold your own references to the server objects in the cache, so that you are the last reference holder.

```rb
bot_servers = {}

bot.ready do
  # This performs a "shallow copy", so that your hash and the cache will point to the same server objects
  # that are mutated as the library receives events that update them, etc.
  bot_servers = bot.servers.clone
end

bot.server_create do |event|
  # Update your references when servers are joined
  bot_servers[event.server.id] = event.server
end

bot.server_delete do |event|
  # Remove the reference from your storage, so that you don't leak the object / hold on to it forever
  deleted_server = bot_servers.delete(event.server)

  # Do something with deleted_server. The reference will be dropped after this event handler ends,
  # releasing the memory to be GC'd at some point
  Discordrb::LOGGER.info("Left #{deleted_server.name}")
end
```

As such, with the current design, `event.server` is left as just the server ID as a compromise with Discord's behavior and the library's current design.
It may be possible to consistently change this in the future.
